### ISSUE TITLE
Component calculator, does not maintain consistency when using clear button.

### ISSUE THREAD

**Issue by zzau13** [atSistemas/angular-base#33]
**I want request a bug.**

**The current behavior is:**

![logs](https://user-images.githubusercontent.com/2625545/37970406-b07c0692-31d3-11e8-84a6-ce77a7cc0bd2.png)
The reducer is caoitic because it mixes selectors and does not follow the standards provided in the redux documentation.

**Expected behaviour:**

Correct simple calculator operation after press operation+clear button.

**Relevant information such as the browser version, Node.js version, and Operating System.**
Linux 4.15.*, Node 8.9.4, Chromium 65

**Comment by pmagaz** [comment]
Hi:

Yes, it seems there is a bug with the clear button of the calculator.

I'm not sure if i'm understanding well what you mean, when you say that reducer its caotic because mixes selectors and  it doesn't follow the standards provided in the redux documentation. Could you give us more detailed explanation?

Thanks.

**Comment by zzau13** [comment]
The reducer is divided into several hierarchical parts, a root selector, using a Map (ES6), [actionHandler](https://github.com/atSistemas/angular-base/blob/master/src/app/containers/calculator/reducers/index.ts#L106). Which routes us through a series of functions:
* [inputOperation](https://github.com/atSistemas/angular-base/blob/master/src/app/containers/calculator/reducers/index.ts#L53) Use swtich-case
* [calculate](https://github.com/atSistemas/angular-base/blob/master/src/app/containers/calculator/reducers/index.ts#L7) Use object and does not have as arguments a state and an action

Therefore we have 3 different selectors and a structure that allows consistency failures.

**Comment by pmagaz** [comment]
Hi:

I understand a little bit better (the word "selectors"  to describe objects or statements is confusing) but for a better understanding could you provide us the link to Redux documentation in what it says something that we are not following? 

Thanks

**Comment by zzau13** [comment]
Sorry, I wanted to refer to the element that implements the strategy are three different, they recommend a switch-case, although it does not specify anything. 
Structure of the reducers is variable for the three located in the same file and does not follow [basic reducer structure](https://redux.js.org/recipes/structuring-reducers/basic-reducer-structure). The function calculate has no structure or returns the previous state in default; inputOperation no returns the previous state in default.
I understand then that they are treated as case functions, [splitting reducer logic](https://redux.js.org/recipes/structuring-reducers/splitting-reducer-logic), but this has to be related to a single action while grouping several leaving hidden much of the implementation. Generating actions are not tested or logged. 
[inputDecimal](https://github.com/atSistemas/angular-base/blob/master/src/app/containers/calculator/reducers/index.ts#L31
), [inputNumber](https://github.com/atSistemas/angular-base/blob/master/src/app/containers/calculator/reducers/index.ts#L40) and [inputOperator](https://github.com/atSistemas/angular-base/blob/master/src/app/containers/calculator/reducers/index.ts#L86) are case functions but they do not have the minimum structure in relation to the action. inputDecimal does not use his action argument. 
Several imports are unused so they must break the tree shaking

You have to change the way you treat the problem using proven methods like [algebraic entry system](https://en.wikipedia.org/wiki/Calculator_input_methods#Immediate_execution), all calculator actions should be called by the CalculatorReducer, refactor case functions with minimum structure, test all actions and fix minor issues. 

I attached an example, [calculator reducer by @deadcoder0904](https://github.com/deadcoder0904/react-native-redux-calculator/blob/master/src/reducers/index.js), which reflects the idea.

**Comment by pmagaz** [comment]
Hi:

After reading your answer i can agree you in some points but i'm not agree you in many things because they are simply not true and to be honest with you i'm not sure if you are fully understanding what's happening there. Let my explain why:

 "Structure of the reducers is variable for the three located in the same file"

There aren't several reducers in this file, there is just one reducer called CalculatorReducer. If you think there are several reducers we have a problem. Please look for a create reducer approach, widely used in medium and large size projects.

"The function calculate has no structure or returns the previous state in default"

I don't know what means that a function that returns an object "has no structure" but that function is NOT a reduce function.... and that's the reason because it doesn't return any state. You can call it a utility function, side effect if you want, but it's NOT a reduce function. Please check 
https://redux.js.org/recipes/structuring-reducers/refactoring-reducers-example#extracting-utility-functions

"inputDecimal, inputNumber and inputOperator are case functions but they do not have the minimum structure in relation to the action"

The create reducer approach splits each switch-case statement into a single function and delegate the type filtering in the create reducer function (the only createReducer function in the file), so there isn't any "relation to the action" or any "minimum structure". Is just nothing more that a pure function with two arguments and a new state returned.  Please look for a create reducer approach.

"we recommend a switch-case"

Redux doesn't recommend any swicth-case
Please check https://redux.js.org/faq/reducers#do-i-have-to-use-the-switch-statement-to-handle-actions

"Generating actions are not tested or logged"

The right term is "create reducer" and yes, they aren't tested but criticise untested functions when you have zero unit tests in your repos and autogenerated e2e tests with "welcome to my app" its ridiculous and very Troll. 

Even if you are right in some points and i'm agree with you, you have opened this issue ussing inappropriate words  and you have argued a lot of inaccuracies about Redux. It's stupid to open an issue in that way or open an Travis issue taking a log of a development branch... We don't have time for this man, so we are closing all your issues for Trolling.

**Comment by zzau13** [comment]
I'm sorry about your anger. I just wanted to help. If you are not open to constructive criticism, don't upload your code.

I think the example is much more correct than its implementation. Sorry if I did not know how to explain better.

**You have closed the issue without fixing the fault produced by the clean.**
But you can do a pull request since the travis works perfectly, [The lost logs](https://github.com/atSistemas/angular-base/pull/32)

Please, don't insult me.
The issues are justified and with a standard format. You should thank me.
If you want you can do the same with my repositories, I will be very grateful.
Regards.

**Comment by pmagaz** [comment]
Hi:

Sorry but you aren't doing any constructive criticism, in fact  your behavior is defined  as a  unacceptable behavior in a lot of COC. We din't have any COC because because we haven`t had any trouble but you. Let's take a look to Redux COC (https://github.com/reactjs/react-redux/blob/master/CODE_OF_CONDUCT.md) for example:

"Examples of unacceptable behavior by participants include the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct."

"derogatory comments " -> You opened an issue using words like caotic which is a derogatory comment. 

"unprofessional conduct" -> Open an issue  criticizing a code that you don't fully understand, as you demonstrated, and  arguing lot of  "inaccuracies" (being very generous with you) about Redux it's  unprofessional conduct. 

"trolling" -> It's pretty clear that you are acting like a Troll but i don't expect you recognize it.

"Please, don't insult me."

Anyone has insulted you, we are more educated that you are but using your own words, try to be more open to "constructive criticism".

"If you want you can do the same with my repositories"

Don't worry, we aren't like you, we have better things to do.

" You should thank me."

Thank you! and please stop this trolling or we will block you.
